version: "3"

services:
    grafana:
        image: grafana/grafana
        container_name: grafana

        # Required valid permission for /var/lib/grafana to create files and folders
        # Since I run from the root so both uid and gid are 0:0
        # but you can use the command i.e. (id) without brackets to find your user correct numbers
        user: "0:0"
        ports:
            - 3000:3000
        volumes:
            - ./data/grafana:/var/lib/grafana

    prom:
        image: prom/prometheus
        container_name: prometheus
        ports:
            - 9090:9090
            # - 9323:9323
        volumes:
            - ./config/prometheus.yml:/etc/prometheus/prometheus.yml

            # fixed the path here as originally you wrote without /etc
            # while in above line you are mentioning /etc/ so was causing errors
            # - ./data/prometheus:/etc/prometheus

    node-exporter:
        image: prom/node-exporter:latest
        container_name: node-exporter
        ports:
            - 9100:9100
    jenkins:
        image: jenkins/jenkins:latest
        container_name: jenkins
        ports:
            - 8080:8080
            - 50000:50000
        volumes:
            - ./jenkins:/var/jenkins_home
